server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #给服务提供者 provider 设置映射
  routes:
    #注：这里的provider是服务提供者的spring.application.name的值
    #通过/p映射provider
    #这样就不用记住它的端口直接访问它的网关/p即可
    #访问方式：当前项目的地址/p/要使用的服务    localhost:8030/p/student/findAll
    provider: /p/**