server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    #配置文件的获取方式
    #native：本地
    active: native
  cloud:
    config:
      server:
        native:
          #本地配置文件存放的路径
          #在类路径下的shared文件夹中
          search-locations: classpath:/shared